name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ALPHA_VANTAGE_API_KEY: test_dummy_key
      PYTHONPATH: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Debug import
        run: |
          python - <<'PY'
          import sys, importlib
          print("sys.path[:4] =", sys.path[:4])
          try:
              m = importlib.import_module("app")
              print("import app: OK ->", m)
          except Exception as e:
              print("import app: FAILED ->", type(e).__name__, e)
          PY

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test with pytest
        run: pytest -vv -m "not integration"
